# Generated by Django 5.0.6 on 2024-06-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.house', verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meters', to='buildings.apartment', verbose_name='адрес'),
        ),
    ]
